"""The Markdown walker, against the block shapes CommonMark reads: which lines are code and
which are prose. Each shape was checked against commonmark.js. The claims checker reads prose
through this walker, so a shape read wrong here is a claim missed, or a false one, there.
"""
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'plugins/bymax-quality/scripts'))
import review_claims as claims


class CodeBlockTests(unittest.TestCase):
    """A name inside a code block is an example, and a name in prose is an assertion."""

    EXAMPLES = (
        ('a backtick fence', '```\nOLD_HELPER()\n```'),
        ('a tilde fence', '~~~\nOLD_HELPER()\n~~~'),
        ('a fence indented under nothing', '  ```\n  OLD_HELPER()\n  ```'),
        ('a fence inside a list item', '- Example:\n\n  ```\n  OLD_HELPER()\n  ```'),
        ('a fence closed only by one as long', '````\nOLD_HELPER()\n```\nstill code\n````'),
        ('a fence with an info string', '```python\nOLD_HELPER()\n```'),
        ('a fence nobody closed', '```\nOLD_HELPER()'),
        ('a fence of the other character inside one', '```\n~~~\nOLD_HELPER()\n~~~\n```'),
        ('an indented block', '    OLD_HELPER()'),
        ('an indented block of several lines', '    one()\n    OLD_HELPER()'),
        ('an indented block after a list closed', '- Status\n\nDone.\n\n    OLD_HELPER()'),
        ('a block indented with a tab', '\tOLD_HELPER()'),
        ('a fence a line with an info string does not close', '```\n``` still open\nOLD_HELPER()\n```'),
        ('a fence four spaces in, which is an indented line and opens nothing',
         '    ```\n    OLD_HELPER()'),
        ('a marker inside an indented block, which opens no list', '    - OLD_HELPER: yes'),
        ('a numbered marker inside an indented block', '    1. OLD_HELPER()'),
        ('a fence inside a block quote', '> Example:\n>\n> ```py\n> OLD_HELPER()\n> ```'),
        ('a fence inside a nested block quote', '> > ```\n> > OLD_HELPER()\n> > ```'),
        ('a quoted fence with no space after the marker', '>```\n>OLD_HELPER()\n>```'),
        ('a quoted fence three spaces in', '   > ~~~\n   > OLD_HELPER()\n   > ~~~'),
        ('an indented block inside a block quote', '>\n>     OLD_HELPER()'),
        ('a quoted fence inside a list item', '- item\n\n  > ```\n  > OLD_HELPER()\n  > ```'),
        ('a quote marker four spaces in, which is an indented block', '    > OLD_HELPER()'),
        ('a quote four columns into a list item, measured from its content',
         '- item\n\n    > ```\n    > OLD_HELPER()\n    > ```'),
        ('a block after a quote that closed the list item', '- item\n> quote\n\n    OLD_HELPER()'),
        ('a block after a quote a blank line below the list item',
         '- item\n\n> quotation\n\n    OLD_HELPER()'),
        ('a quoted block reached by two tabs after the marker', '>\n>\t\tOLD_HELPER()'),
        ('a space and a tab after a marker two columns in, which reach a block',
         '  > \tOLD_HELPER()'),
        ('a tab in a nested quote, measured from the line and not the level', '> >\n> > \tOLD_HELPER()'),
        ('a block after a quote that left an item quote', '- item\n\n  > quote\n> more\n\n    OLD_HELPER()'),
        ('a block after a quote that left an item quote with no blank line', '- item\n  > quote\n> more\n\n    OLD_HELPER()'),
        ('a block after an empty quote, where no paragraph is open', '>\n    OLD_HELPER()'),
        ('a block right after a closed fence', '```\nx\n```\n    OLD_HELPER()'),
        ('a fence in a list item after a lazy line', '- item\nlazy text\n    ```\n    OLD_HELPER()'),
        ('a block after a heading that closed the list item',
         '- Install it\n## Usage\n\n    OLD_HELPER()'),
        ('a block right under a heading, where no paragraph is open',
         '## Usage\n    ```\n    OLD_HELPER()\n    ```'),
        ('a block right under a thematic break',
         '---\n    OLD_HELPER()'),
        ('a block under a list item a blank line closed',
         '  1. one\n\n    ```\n    OLD_HELPER()\n    ```'),
        ('a fence inside the inner of two items opened on one line',
         '- 1. one\n      ```\n      OLD_HELPER()\n      ```'),
        ('a fence in the outer item after the inner one closed',
         '- a\n  - b\n\n  ```\n  OLD_HELPER()\n  ```'),
        ('a fence that ends a quoted paragraph rather than continuing it',
         '> para\n```\nOLD_HELPER()\n```'),
        ('a block after a closing raw-text tag, which starts no HTML block',
         '</pre> text\n\n    OLD_HELPER()'),
        ('a fence under a declaration CommonMark does not start',
         '<!>\n```\nOLD_HELPER()\n```'),
        ('a fence after an item a blank-line HTML block ended with',
         '- a\n\n  <div>\n```\nOLD_HELPER()\n```'),
        ('a fence under a paragraph a lone inline tag cannot interrupt',
         'para\n<span>\n```\nOLD_HELPER()\n```'),
        ('a fence under a paragraph an indented tag continues',
         'text\n    <div>\n```\nOLD_HELPER()\n```'),
        ('a fence opened on a list marker line',
         '1. ```sh\n   OLD_HELPER()\n   ```'),
        ('a block after an empty item that could not interrupt a paragraph',
         'Title\n-  \n\n    OLD_HELPER()'),
        ('a block right under a marker with nothing after it', '-\n      OLD_HELPER()'),
        ('a block after five spaces behind a marker',
         '-     OLD_HELPER()'),
        ('a block after an empty item a blank line ended',
         'Intro\n\n-\n\n    OLD_HELPER()'),
        ('a block after an empty ordered item a blank line ended',
         '1.\n\n    OLD_HELPER()'),
        ('a block after a setext underline read as an empty item',
         '- Setup\n  -\n\n      OLD_HELPER()'),
        ('a block right under an empty item that follows a paragraph item',
         '- a\n-\n      OLD_HELPER()'),
        ('a second marker past a wide gap, which is a block',
         '1.     2. OLD_HELPER()'),
        ('a block after an empty nested quote', '> >\n    OLD_HELPER()'),
        ('a marker four columns past the content it reaches, which is a block',
         '   *  x\n      # deep\n\t- OLD_HELPER()'),
        ('a nested list not numbered 1, which continues the item paragraph',
         '- a\n  2. b\n\n      OLD_HELPER()'),
        ('a fence line indented four columns inside a fence, which does not close it',
         '```\n\t```\nOLD_HELPER()'),
        ('the example after a fence that holds indented fence lines',
         '```markdown\n- item\n\n\t```\n\tcode\n\t```\n```\n\n```\nOLD_HELPER()\n```'),
        ('a form feed line that continues nothing before a block',
         '> q\n\x0c\n0.     OLD_HELPER()'),
        ('a CRLF fence inside an item',
         '- ```\r\n\r\n  OLD_HELPER()\r\n  ```'),
        ('an empty CRLF item that a blank line ends',
         '- \r\n\r\n    OLD_HELPER()'),
        ('a CRLF heading marker before a tab block',
         '#\r\n\tOLD_HELPER()'),
        ('a CRLF thematic break before a wide item',
         '***\r\n2)     OLD_HELPER()'),
        ('an example in a document ended by lone carriage returns',
         'text\r\r    OLD_HELPER()'),
        ('a block under a setext heading, where no paragraph is open',
         'Title\n===\n    OLD_HELPER()'),
        ('a block under a heading underlined with one dash',
         'Title\n-\n    OLD_HELPER()'),
        ('a block under a setext heading inside a list item',
         '- Title\n  ===\n      OLD_HELPER()'),
        ('a block under a setext heading inside a quote',
         '> Title\n> ===\n>     OLD_HELPER()'),
        ('an underline three columns into a list item',
         '- Title\n     ===\n      OLD_HELPER()'),
        ('a heading under a paragraph and a definition-free text line',
         '[r]: /u\ntext\n===\n    OLD_HELPER()'),
        ('a quote marker four columns in after a quote, which is a block',
         '>\n    > OLD_HELPER()'),
        ('a nested item whose first line is a block past a wide gap',
         '- a\n  -     OLD_HELPER()'),
        ('an underline after a title that never closes, which is a heading',
         '[foo]: /url\n"not a title\n===\n    OLD_HELPER()'),
        ('an underline under a label with no destination, which is a heading',
         '[foo]:\n===\n    OLD_HELPER()'),
        ('a second title line under a definition, which a heading underlines',
         '[foo]: /url\n"t1"\n"t2"\n===\n    OLD_HELPER()'),
        ('a title line after a definition that had its title',
         '[foo]: /url "t"\n"t2"\n===\n    OLD_HELPER()'),
        ('a title after a destination on its own line with its title',
         '[foo]:\n/url "t"\n"t2"\n===\n    OLD_HELPER()'),
        ('a lone tag lazily continuing an item paragraph before a fence',
         '- a\n<x-y z="1" />\n```\nOLD_HELPER()'),
        ('a destination with unbalanced parentheses, which is no definition',
         '[r]: /u(\n===\n    OLD_HELPER()'),
        ('a label of spaces only, which is no definition',
         '[ ]: /u\n===\n    OLD_HELPER()'),
        ('a label holding an unescaped bracket, which is no definition',
         '[a[b]: /u\n===\n    OLD_HELPER()'),
        ('a title left open, which the underline makes a heading',
         '[r]: /u\n"bad\n===\n    OLD_HELPER()'),
        ('a bracket that never closes a label, which the underline heads',
         '[a\nb\n===\n    OLD_HELPER()'),
        ('a label of space alone over two lines, which is no definition',
         '[\n]: /u\n===\n    OLD_HELPER()'),
        ('a closed label with no colon, which is no definition',
         '[a\nb] c\n===\n    OLD_HELPER()'),
        ('a pointy destination that never closes, which is no definition',
         '[r]: <u\n===\n    OLD_HELPER()'),
        ('a parenthesised title holding an open parenthesis, which is no title',
         '[r]: /u (a(b)\n===\n    OLD_HELPER()'),
        ('text after a closed title, which leaves no definition',
         '[r]: /u "t" x\n===\n    OLD_HELPER()'),
        ('a destination closing a parenthesis it never opened',
         '[r]: /u)(\n===\n    OLD_HELPER()'),
        ('a title with no space after a pointy destination',
         '[r]: <u>"t"\n===\n    OLD_HELPER()'),
        ('a tag after an item holding only a definition, which stays in its paragraph',
         '- [r]: /u\n<img src="x">\n=\n-     OLD_HELPER()'),
        ('a tag after a nested quote holding only a definition, which stays in its paragraph',
         '> > [r]: /u\n<img src="x">\n-     OLD_HELPER()'),
        ('a fence under a closing raw-text tag, which opens a paragraph',
         '</pre> text\n```\nOLD_HELPER()\n```'),
        ('a block after an HTML block that closed a list item',
         '- Install it\n<div>\n\n    OLD_HELPER()'),
        ('a fence after a line that left the item a comment opened in',
         '- a\n\n  <!--\nbar\n```\nOLD_HELPER()\n```'),
        ('a block after a comment that ran over a blank line inside its item',
         '- a\n\n  <!--\n\n  still comment\n  -->\n\n      OLD_HELPER()'),
        ('a fence under a paragraph that opens with an inline tag',
         '<b>bold</b> text\n```\nOLD_HELPER()\n```'),
        ('a block after a comment that closed on its own line',
         '<!-- a note -->\n\n    OLD_HELPER()'),
        ('a block after an HTML block a blank line ended',
         '<div>\n\n    OLD_HELPER()'),
        ('a block after a comment closed on a later line',
         '<!--\nx\n-->\n\n    OLD_HELPER()'),
        ('a block after a thematic break spelled with list markers',
         '- a\n- - -\n\n    OLD_HELPER()'),
        ('a tilde fence whose info string holds a backtick',
         '~~~ python`ok\nOLD_HELPER()\n~~~'),
    )

    ASSERTIONS = (
        ('a mention on its own', 'The OLD_HELPER is gone.'),
        ('a continuation four spaces under a list marker',
         '- Status\n\n    We removed OLD_HELPER from the API.'),
        ('a nested list item', '- Status\n    - and OLD_HELPER went with it'),
        ('the wrapped second line of a sentence',
         'A paragraph about it\n    that says OLD_HELPER is gone.'),
        ('the prose after a fence four spaces in, which never opened',
         '    ```\nWe removed OLD_HELPER from the API.'),
        ('a mention inside a block quote', '> We removed OLD_HELPER.'),
        ('a lazy line continuing a quoted paragraph', '> A paragraph\nthat says OLD_HELPER is gone.'),
        ('the prose after a quote whose fence never closed',
         '> ```\n> example()\nWe removed OLD_HELPER from the API.'),
        ('a quoted line three spaces past the marker, which is not a block',
         '>\n>    We removed OLD_HELPER from the API.'),
        ('a quote marker four spaces under a paragraph, which continues it',
         'A paragraph\n    > ```\n    > OLD_HELPER()'),
        ('a lazy line four spaces in after a quoted paragraph', '> para\n    We removed OLD_HELPER.'),
        ('a tab after the marker, which is two columns from it', '>\tWe removed OLD_HELPER.'),
        ('a space and a tab after the marker', '> \tWe removed OLD_HELPER.'),
        ('a tab after a marker two columns in', '  >\tWe removed OLD_HELPER.'),
        ('a nested quote whose tabs leave a paragraph', '> >\n>\t> \tWe removed OLD_HELPER.'),
        ('a quote after an item quote whose fence never closed', '- item\n\n  > ```\n  > code\n> We removed OLD_HELPER.'),
        ('a fence four columns in under a quoted paragraph', '> para\n>      ```\n> We removed OLD_HELPER.'),
        ('a fence four columns in under a paragraph', 'A paragraph\n    ```\nWe removed OLD_HELPER.'),
        ('a quote line after a lazy line, continuing its paragraph', '> para\nlazy text\n>     We removed OLD_HELPER.'),
        ('a quote nested past the depth the walk reads', '>' * 2000 + ' We removed OLD_HELPER.'),
        ('prose after a heading closed the item a fence opened in',
         '- Install it\n## Usage\n\n    ```\n    keep()\n\nCall OLD_HELPER to reset.'),
        ('prose that leaves the item its fence opened in',
         '1. item\n\n      ```\nWe removed OLD_HELPER.'),
        ('a list item that ends a quoted paragraph',
         '> para\n- item\n\n    We removed OLD_HELPER.'),
        ('a quote marker four spaces under a quoted paragraph',
         '> para\n    > We removed OLD_HELPER.'),
        ('text inside an HTML block',
         '<div>\n    We removed OLD_HELPER.\n</div>'),
        ('a comment running over a blank line',
         '<!--\n\n    We removed OLD_HELPER.\n-->'),
        ('a heading four columns in, which continues the paragraph',
         'Run the following:\n    # install\n    OLD_HELPER --init'),
        ('a thematic break four columns in, which continues the paragraph',
         'Run the following:\n    ---\n    OLD_HELPER --init'),
        ('a heading four columns past an item paragraph',
         '- Setup:\n  run this\n      # install\n      OLD_HELPER --init'),
        ('an HTML start four columns in, continuing a quoted paragraph',
         '>.\n    <!\n>     OLD_HELPER'),
        ('a pre tag closed on itself, which starts no HTML block',
         '> Note:\n> <pre/>\n    We removed OLD_HELPER.'),
        ('an item whose marker is followed by five spaces',
         '-     Install it\n\n    We removed OLD_HELPER.'),
        ('an empty item, whose content starts one past its marker',
         '-  \n  ---\n    We removed OLD_HELPER.'),
        ('a bare marker, which still opens an item',
         '-\n  ***\n    We removed OLD_HELPER.'),
        ('the outer item a closed inner one returns to',
         '- a\n  - b\n\n  c\n\n    We removed OLD_HELPER.'),
        ('a processing instruction running over a blank line',
         '<?php\n\n    We removed OLD_HELPER.\n?>'),
        ('a declaration running over a blank line',
         '<!DOCTYPE x\n\n    We removed OLD_HELPER.\n>'),
        ('an item opened by a marker and a tab',
         '1.\tStep one\n\n\tMore about OLD_HELPER.'),
        ('prose after a fence closed inside the item its marker line opened',
         '1. ```sh\n   x()\n   ```\n   We removed OLD_HELPER.'),
        ('an ordered marker not numbered 1, which continues a paragraph',
         'Title\n2. two\n    ```\n    We removed OLD_HELPER.'),
        ('a tag four columns in, continuing a quoted paragraph',
         '>.\n    <div>\n>     We removed OLD_HELPER.'),
        ('an ordered marker that leaves a quoted paragraph and opens a list',
         '> Tip: read the docs.\n2. Install\n\n    We removed OLD_HELPER.'),
        ('a lazy tag line inside a quoted item, which only continues it',
         '> 1. Step\n    <div>\n    We removed OLD_HELPER.'),
        ('a lazy fence line inside a quoted item, which only continues it',
         '> 1. q\n    ```\n    We removed OLD_HELPER.'),
        ('a tab after a marker behind a quote',
         '> - > \tWe removed OLD_HELPER.'),
        ('a marker four columns in under a wide item, which continues it',
         '-    Install it\n    -     We removed OLD_HELPER.'),
        ('a tab after a marker, measured from the line',
         '-\tStep one\n\n      We removed OLD_HELPER.'),
        ('a CDATA block running over a blank line',
         '<![CDATA[\n\n    We removed OLD_HELPER.\n]]>'),
        ('a list opened by the line that closed a quote',
         '   > q\n2. two\n\n    We removed OLD_HELPER.'),
        ('an empty item that cannot interrupt a paragraph, and what continues it',
         'Title\n1. \n       We removed OLD_HELPER.'),
        ('a list numbered 01, which interrupts a paragraph',
         'a\n01. b\n\n     We removed OLD_HELPER.'),
        ('prose after a fence that holds indented fence lines',
         '```markdown\n- item\n\n\t```\n\tcode\n\t```\n```\n\nWe removed OLD_HELPER.'),
        ('an item whose first line is a block past a wide gap',
         '-      -\n\n    We removed OLD_HELPER.'),
        ('an ordered item whose first line is a block past a wide gap',
         '1.      1.\n\n     We removed OLD_HELPER.'),
        ('a line of non-breaking spaces, which is not blank',
         '+ \n\xa0\n\tWe removed OLD_HELPER.'),
        ('a line holding a form feed, which is not blank',
         '- \n\x0c\n\tWe removed OLD_HELPER.'),
        ('a lazy line continuing a nested quote paragraph',
         '> > q\n    We removed OLD_HELPER.'),
        ('a heading line that lazily continues a wide item, which stays open',
         '-    Install it\n    # x\n\n     We removed OLD_HELPER.'),
        ('a run of markers deeper than the interpreter recurses', '- ' * 2000 + 'We removed OLD_HELPER.'),
        ('a line of non-breaking spaces inside a quote paragraph',
         '> q\n\xa0\n>     We removed OLD_HELPER.'),
        ('an item whose text is a non-breaking space, under a paragraph',
         'a\n- \xa0\n\n    We removed OLD_HELPER.'),
        ('a fence whose closing line ends in a non-breaking space',
         '```\nx\n```\xa0\ny\n```\n\nWe removed OLD_HELPER.'),
        ('a non-breaking-space line leaving an item fence',
         '- ```\n\xa0\n  We removed OLD_HELPER.\n  ```'),
        ('an item holding only a non-breaking space',
         '- \xa0\n\n    We removed OLD_HELPER.'),
        ('an item whose gap ends in a non-breaking space',
         '-   \xa0\n\n      We removed OLD_HELPER.'),
        ('a heading marker behind a non-breaking space',
         'a\n\xa0# x\n    We removed OLD_HELPER.'),
        ('a quote marker behind a non-breaking space in an item',
         '- a\n\xa0> x\n\n    We removed OLD_HELPER.'),
        ('a quote marker behind a non-breaking space under a paragraph',
         'a\n\xa0>     We removed OLD_HELPER.'),
        ('a fence line ending in two carriage returns, which still closes',
         '```\r\r\ncode\n```\r\r\nWe removed OLD_HELPER.'),
        ('lines ended by a lone carriage return',
         '```\rcode\r```\rWe removed OLD_HELPER.'),
        ('a CRLF paragraph and its indented continuation',
         'A paragraph\r\n    We removed OLD_HELPER.'),
        ('a list not numbered 1 after a setext heading',
         'Steps\n=====\n2. Run the installer.\n\n    We removed OLD_HELPER in this release.'),
        ('a wide item after a lone tag under a setext heading',
         'Title\n=====\n<img src="logo.png">\n-     We removed OLD_HELPER.'),
        ('a quote after a lone tag under a setext heading',
         'Title\n===\n<img src="x">\n>     We removed OLD_HELPER.'),
        ('a lazy underline, which is text of the quoted paragraph',
         '> Title\n===\n    We removed OLD_HELPER.'),
        ('an underline four columns in, which continues the paragraph',
         'Title\n    ===\n    We removed OLD_HELPER.'),
        ('a lazy underline in a list item, which is text',
         '- Title\n===\n      We removed OLD_HELPER.'),
        ('an underline with no paragraph above it, which starts one',
         '===\n    We removed OLD_HELPER.'),
        ('a marker line whose text is a second marker, then an underline',
         'Paragraph.\n- -\n=\n    We removed OLD_HELPER.'),
        ('an ordered marker as a first item text, then an underline',
         'Para\n- 1.\n--\n    We removed OLD_HELPER.'),
        ('a starred item holding a dash, then a dash',
         'Para\n* -\n-\n    We removed OLD_HELPER.'),
        ('an underline followed by text, which is not one',
         'Title\n=== x\n    We removed OLD_HELPER.'),
        ('an underline with a space inside, which is not one',
         'Title\n= =\n    We removed OLD_HELPER.'),
        ('an underline mixing both characters, which is not one',
         'Title\n=-\n    We removed OLD_HELPER.'),
        ('a lazy fence line four columns short of a wide item',
         '100. Install\n    ```\n    We removed OLD_HELPER.'),
        ('a lone tag that leaves a quote and holds what follows',
         '> q\n<x-y z="1" />\n- ```\nWe removed OLD_HELPER.'),
        ('a dash under a link reference definition, which is no heading',
         '[ref]: /url\n  -\n    We removed OLD_HELPER.'),
        ('a dash under a definition and its title',
         '[ref]: /url\n  "title"\n  -\n    We removed OLD_HELPER.'),
        ('a quote marker behind a non-breaking space, which is text',
         '\xa0> ```\n\xa0> We removed OLD_HELPER.'),
        ('an underline under a definition whose destination is on its own line',
         '[foo]:\n/url\n===\n    We removed OLD_HELPER.'),
        ('an underline under a definition with a title in parentheses',
         '[foo]: /url\n(title)\n===\n    We removed OLD_HELPER.'),
        ('an underline under a definition and its one title line',
         '[foo]: /url\n"t1"\n===\n    We removed OLD_HELPER.'),
        ('a title with escaped quotes',
         '[r]: /u "a \\"b\\""\n===\n    We removed OLD_HELPER.'),
        ('a definition whose destination is lazy inside a quote',
         '> [r]:\n/u\n> ===\n>     We removed OLD_HELPER.'),
        ('a destination with nested parentheses',
         '[r]: /u((x))\n===\n    We removed OLD_HELPER.'),
        ('a title spanning two lines',
         '[r]: /u "two\nlines"\n===\n    We removed OLD_HELPER.'),
        ('prose after a fence that follows a lazy tag in an item',
         '- Screenshot:\n<img src="shot.png" />\n```bash\nold()\n\nNEW()\n```\n\nWe removed OLD_HELPER.'),
        ('a label running over two lines',
         '[a\nb]: /u\n===\n    We removed OLD_HELPER.'),
        ('a label whose text starts on its second line',
         '[\na]: /u\n===\n    We removed OLD_HELPER.'),
        ('a second definition after a titled one',
         '[r]: /u "t"\n[s]: /v\n===\n    We removed OLD_HELPER.'),
        ('an escaped parenthesis in a destination',
         '[r]: /u\\(\n===\n    We removed OLD_HELPER.'),
        ('an escaped bracket in a pointy destination',
         '[r]: <a\\>b>\n===\n    We removed OLD_HELPER.'),
        ('a label line ending in a backslash',
         '[a\\\nb]: /u\n===\n    We removed OLD_HELPER.'),
        ('a lowercase declaration running over a blank line',
         '<!x\n\n    We removed OLD_HELPER.\n>'),
        ('indented text in a comment over a blank line inside its item',
         '- a\n\n  <!--\n\n      We removed OLD_HELPER.\n  -->'),
        ('raw text in a pre block over a blank line',
         '<pre>\n\n    We removed OLD_HELPER.\n</pre>'),
        ('a paragraph a lazy HTML tag cannot interrupt',
         '> para\n<span>\n    We removed OLD_HELPER.'),
        ('a backtick fence whose info string holds a backtick',
         '```python`bad\nWe removed OLD_HELPER.\n```'),
        ('a quoted paragraph a backtick run with a backtick in its info continues',
         '> para\n```a`b\n>     We removed OLD_HELPER.'),
        ('an item a backtick run with a backtick in its info continues',
         '- item\n```x`y\nWe removed OLD_HELPER.'),
    )

    def test_a_name_inside_a_code_block_is_an_example(self):
        """Every regex spelling tried for this fixed a shape and broke another. The shapes are
        listed in EXAMPLES and ASSERTIONS above and walked here, so a new spelling has to
        answer all of them at once."""
        for name, shown in self.EXAMPLES:
            with self.subTest(name):
                self.assertNotIn('OLD_HELPER', claims.prose('README.md', '# doc\n\n' + shown + '\n'))
        for name, said in self.ASSERTIONS:
            with self.subTest(name):
                self.assertIn('OLD_HELPER', claims.prose('README.md', '# doc\n\n' + said + '\n'))


if __name__ == '__main__':
    unittest.main()
